MvcProjeKampi/Controllers/AboutController.cs
using Business.Concrete;
using DataAccsess.EntityFramework;
using Entities.Concrete;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EfAboutDal());

        public ActionResult Index()
        {
            var result = aboutManager.GetAll();
            return View(result);
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(About about)
        {
            aboutManager.Add(about);
            return RedirectToAction("Index");
        }
        public PartialViewResult AboutPartial()
        {
            return PartialView();
        }
        public ActionResult Status(int id = 0)
        {
            var result = aboutManager.Get(id);
            if (result.Status == true)
            {
                result.Status = false;
            }
            else
            {
                result.Status = true;
            }
            aboutManager.Update(result);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/GaleryController.cs
using Business.Concrete;
using DataAccsess.Concrete;
using DataAccsess.EntityFramework;
using Entities.Concrete;
using MvcProjeKampi.ViewModels;
using System.IO;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    
    public class GaleryController : Controller
    {
        ImageFileManager imageFileManager = new ImageFileManager(new EfImageFileDal());

        public ActionResult Index()
        {
            var result = imageFileManager.GetAll();
            return View(result);
        }

        public ActionResult AddImage()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddImage(ImageVM imageVM)
        {

            string fotoAdi = Seo.DosyaAdiDuzenle(imageVM.GaleryImage.FileName);
            imageVM.ImageName = fotoAdi;
            ImageFile file = new ImageFile
            {
                ImageName = imageVM.ImageName,
                ImagePath= "/Admin/img/"+ imageVM.ImageName
            };
            imageFileManager.Add(file);
            imageVM.GaleryImage.SaveAs(Path.Combine(Server.MapPath("~/Admin/img/"), Path.GetFileName(fotoAdi)));
            TempData["mesaj"] = "Resim Eklendi";


            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/LoginController.cs
using Business.Concrete;
using DataAccsess.EntityFramework;
using Entities.Concrete;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcProjeKampi.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly LoginManager loginManager = new LoginManager(new EfAdminDal());
        private readonly WriterLoginManager writerLoginManager = new WriterLoginManager(new EfWriterDal());

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Admin admin)
        {
            var result = loginManager.Login(admin);

            if (result != null)
            {
                FormsAuthentication.SetAuthCookie(result.AdminUserName, false);
                Session["AdminUserName"] = result.AdminUserName;
                return RedirectToAction("Index", "AdminCategory");
            }
            else
            {
                ViewBag.Error = "Kullanıcı adı veya şifre yanlış";
                ViewBag.Role = "Ve ya bu sayfaya giriş için yetkinizi kontrol edin";
                return View();
            }

        }
        public ActionResult WriterLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult WriterLogin(Writer writer)
        {

            //var result = context.Writers.FirstOrDefault(c => c.WriterMail == writer.WriterMail && c.WriterPassword == writer.WriterPassword);
            var result = writerLoginManager.GetWriter(writer.WriterMail, writer.WriterPassword);
            if (result != null)
            {
                FormsAuthentication.SetAuthCookie(result.WriterMail, false);
                Session["WriterMail"] = result.WriterMail;
                return RedirectToAction("MyContent", "WriterPanelContent");
            }
            else
            {
                ViewBag.Error = "Kullanıcı adı veya şifre yanlış";
                return View();
            }

        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return View("Headings", "Home");
        }
    }
}

MvcProjeKampi/Controllers/SkillController.cs
using Business.Concrete;
using DataAccsess.EntityFramework;
using MvcProjeKampi.ViewModels;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class SkillController : Controller
    {
        PersonManager personManager = new PersonManager(new EfPersonDal());
        SkillManager skillManager = new SkillManager(new EfSkillDal());

        public ActionResult Index()
        {
            SkillVM viewModel = new SkillVM
            {
                Skills = skillManager.GetAll(),
                Persons = personManager.Get()
            };
            return View(viewModel);
        }
    }
}

MvcProjeKampi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@ViewBag.Title</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/Admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Admin Panel</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Admin/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    @if (Request.IsAuthenticated)
                    {
                        <div class="info">
                            @Html.ActionLink(User.Identity.Name, "", "")
                        </div>
                    }

                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        @if (User.IsInRole("B"))
                        {
                            <li class="nav-item has-treeview">
                                <a href="@Url.Action("Index","AdminCategory")" class="nav-link">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Kategoriler
                                    </p>
                                </a>
                            </li>

                        }
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Heading")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("GetAllContent","Content")" class="nav-link">
                                <i class="nav-icon fas fa-book-reader"></i>
                                <p>
                                    Yazılar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Writer")" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Yazarlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Grafikler
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="/Chart/Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="Chart/Index2" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="Chart/Index3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Index","About")" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Hakkımızda
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("HeadingReport","Heading")" class="nav-link">
                                <i class="nav-icon fas fa-bars"></i>
                                <p>
                                    Raporlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Index","Contact")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    İletişim & Mesajlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Authorization")" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirmeler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Galery")" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Page404","ErrorPage")" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Hata Sayfaları
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Index","Skill")" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Yetenek Kartım
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Index","Home")" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye Git
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("LogOut","Login")" class="nav-link">
                                <i class="nav-icon far fa-plus-square"></i>
                                <p>
                                    Çıkış Yap
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    @*<script src="~/Admin/plugins/jquery/jquery.min.js"></script>*@
    <!-- Bootstrap -->
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/Admin/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/Admin/plugins/chart.js/Chart.min.js"></script>
    <script src="~/Admin/dist/js/demo.js"></script>
    <script src="~/Admin/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MvcProjeKampi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProjeKampi/Views/Shared/_WriterLoyout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>MVC Proje Kampı</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/Admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">MVC Proje Kampı</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Admin/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Yazar Paneli</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item has-treeview">
                            <a href="/WriterPanel/WriterProfile" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Profilim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("MyHeading","WriterPanel")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklarım
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("AllHeading","WriterPanel")" class="nav-link">
                                <i class="nav-icon fas fa-list-alt"></i>
                                <p>
                                    Tüm Başlıklar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Inbox","WriterPanelMessage")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Mesajlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("MyContent","WriterPanelContent")" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yazılarım
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Headings","Home")" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye Git
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("LogOut","Login")" class="nav-link">
                                <i class="nav-icon far fa-plus-square"></i>
                                <p>
                                    Çıkış Yap
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/Admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/Admin/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/Admin/plugins/chart.js/Chart.min.js"></script>
    <script src="~/Admin/dist/js/demo.js"></script>
    <script src="~/Admin/dist/js/pages/dashboard3.js"></script>
</body>
</html>