MvcProjeKampi/Controllers/WriterPanelContentController.cs
using Business.Concrete;
using DataAccsess.Concrete;
using DataAccsess.EntityFramework;
using Entities.Concrete;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelContentController : Controller
    {
        private readonly ContentManager contentManager = new ContentManager(new EfContentDal());
        private readonly Context context = new Context();

        public ActionResult MyContent(string mail)
        {
            mail = (string)Session["WriterMail"];
            var writerInfo = context.Writers.Where(c => c.WriterMail == mail).Select(y => y.WriterId).FirstOrDefault();
            var result = contentManager.GetListByWriter(writerInfo);
            return View(result);
        }
        public ActionResult AddContent(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            content.ContentDate = DateTime.Now;
            string mail = (string)Session["WriterMail"];
            var writerInfo = context.Writers.Where(c => c.WriterMail == mail).Select(y => y.WriterId).FirstOrDefault();
            content.WriterId = writerInfo;
            content.Status = true;
            contentManager.Add(content);
            return RedirectToAction("MyContent");
        }

        public ActionResult ToDoList()
        {

            return View();
        }
    }
}

MvcProjeKampi/Views/WriterPanelContent/AddContent.cshtml
@model Entities.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLoyout.cshtml";
}
<h1>İçerik girişi sayfası</h1>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post, new { @class = "m-3" }))
{
    <div class="form-group">
        <input type="hidden" name="HeadingId" value="@ViewBag.Id" />
        @Html.Label("İçeriğinizi yazınız")
        @Html.TextAreaFor(m => m.ContentValue,10,30,new { @class = "form-control",required="required" })
        <br />
        <button type="submit" class="btn btn-success">Kaydet</button>
    </div>
}

MvcProjeKampi/Views/WriterPanelContent/MyContent.cshtml
@model List<Entities.Concrete.Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLoyout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@item.ContentDate.ToString("dd-MM-yyyy")</span>
                                </div>
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeKampi/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLoyout.cshtml";
}

<p><del>#1 Profilim</del></p>
<p><del>#2 Tüm başlıklarda sayfalama</del></p>
<p><del>#3 Mesajlarda Session</del></p>
<p><del>#4 Oturum yönetiminin mimariye taşınması</del></p>